### PR TITLE
Standardize error message grammar, add test for bad composite parameters, fix a few other grammar things

### PR DESCRIPTION
**Pull request by wingfactor**
Hello!

My name is Jordan, and I'm new on this project. I met with @davidanthoff on Monday and he set me loose on the issue stack.

Edit: Here, I fixed a few grammatical issues, then set up a test to improve code coverage. I intended this mostly as an introduction and a hands-on way to begin to familiarize myself with Mimi's code.

### CODE REVIEW

**Comment by wingfactor** [comment]
Currently 3 of 11 edits are not covered by tests. I'm going to work on fixing this. It's odd that this gave "70.00% of diff hit", which would suggest 3/10 misses, not 3/11.

**Comment by lrennels** [comment]
Great! Welcome @wingfactor I can take a look at this on Monday, happy to see you digging your hands in!

**Review by lrennels — APPROVED** [review]

**Comment by lrennels** [comment]
@wingfactor would you like me to merge this or would you rather keep it open for a while as your learning branch?

**Comment by wingfactor** [comment]
@lrennels You can go ahead and merge it, thank you for checking. I've got a fork of the project to keep experimenting with and to submit future pull requests from.

**Pull request merged**
