### PR TITLE
Add a test for external parameters

### PR DESCRIPTION
**Pull request by davidanthoff**
This is a small test that captures the problem that makes https://github.com/fund-model/MimiFUND.jl/pull/64 not pass right now.

First question: do we all agree that the behavior in this test is what we want? I think yes, right?

Next step, someone (other than me) pushes something to this branch here that makes the test pass :)

@rjplevin, @ckingdon95 and @lrennels .

### CODE REVIEW

**Comment by ckingdon95** [comment]
just making a note that I'll probably want to move this test into an existing test file (we have so many different test files!)

**Comment by ckingdon95** [comment]
It's definitely a problem with parameters that have defaults. I added a line that shows that after you run the model (aka after it's been built), the parameter ends up in the external parameters list. I think it's actually a bit confusing what behavior we want in this case. When we add a component that has default parameters to a model, do we want those parameters to populate the model's external parameter dictionary at that moment?

**Comment by rjplevin** [comment]
> When we add a component that has default parameters to a model, do we want those parameters to populate the model's external parameter dictionary at that moment?

Each `CompositeComponentDef` stores a vector of defaults. At build time (see `_set_defaults()` in build.jl) these are gathered into a `dict` that hashes on the component path and parameter name, and then applied to unconnected parameters.

I suspect that the leaf components may not be handled correctly in this processing.

**Comment by ckingdon95** [comment]
Decided:
- you cannot call `update_param!` on something unless you have already used `set_param!` for that parameter
- so the current behavior of erroring is actually correct, and we need to change the test in FUND to use `set_param!`

**Pull request closed without merging**
