### PR TITLE
add `delete_unbound_comp_params` kwarg to `delete!`

### PR DESCRIPTION
**Pull request by ckingdon95**
#752 

Two additions in this PR:
1. This adds `delete_unbound_comp_params::Bool=false` keyword argument to the `delete!` function, which when set to true then deletes all external parameters that were only connected to the deleted component. 
2. I also created a new function `delete_param!(m, external_param_name, delete_connections=true)` for removing parameters from a model's list of external parameters.

To discuss:

- kwarg name: I went with the verbose `delete_unbound_comp_params` for now, which is definitely not perfect. The reason I'm feeling averse to `deep` or `recursive` is that it doesn't delete _all_ parameters associated with this component, only the ones not connected to any other components.
- in order to add this functionality, I had to change the function signature to only operate on ModelDefs, and not on all AbstractCompositeComponentDefs because the latter do not have external parameter lists.
- for the new `delete_param!` function, is this okay to make the default `delete_connections=true`, and do we want a different name for that keyword arg?

### CODE REVIEW

**Comment by davidanthoff** [comment]
For the new `delete_param!` function, I don't fully understand what `delete_connections=true` does. Don't we always have to delete connections that included the deleted parameter, because otherwise we would have "stray" connections hanging around?

**Comment by ckingdon95** [comment]
@davidanthoff Yes, it would be a weird behavior to leave the connections hanging. Shall I remove the option all together for now? (Since this is new, we could always add in options later if we realize they might be needed)

**Comment by ckingdon95** [comment]
@davidanthoff ok I got impatient and was assuming you were going to answer yes so I removed that option for now

**Comment by ckingdon95** [comment]
One design question is whether it would be better to not have a separate `delete_param!` function and if this functionality should be folded into the `delete!` function. basically it would be:
```
function delete!(md::ModelDef, item_name::Symbol)
    item = md.namespace[item_name]
    if item isa component
        _delete_component . . .
    elseif item isa param
        _delete_param . . .
    end
end
```
The only thing is that we now have this `delete_unbound_comp_params` option that only makes sense in the component case

**Comment by ckingdon95** [comment]
decided in group meeting: stick with `delete_param!` because we don't have a shared namespace for components and parameters

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
