### PR TITLE
WIP Use Different Approach to Check for Broadcasting in Perturb Param

### PR DESCRIPTION
**Pull request by lrennels**
@jrising work in progress but I think this will solve https://forum.mimiframework.org/t/setting-a-distributions-over-large-dimensions-in-defsim/277/10

- [x] run Mimi tests locally
- [x] test on PAGE2020 (does fix the original error, the `init` function now errors but happy to help with that too)
- [x] test on MimiGIVE including regression testing to make sure all pass

### CODE REVIEW

**Comment by jrising** [comment]
This seems like the right solution to me. Did you figure out if it's related to String vs. String15's? I thought it was due to my use of a single dimension when you just used this for double dimension parameters.

**Comment by lrennels** [comment]
No I think jt is the String15, because I use this for single dimensions too, that’s how I did my comparison I ran this step by step alongside the same for the mortality Beta in GIVE and it seems String15 returns a vector for a single index when String returns an Int.  I use CSVFiles and I have never seen that load a String type other than the base String. 

But I think this solution gets closer to the heart of when Julia says you should broadcast so that’s better regardless? Happy to keep plugging a bit.

**Comment by lrennels** [comment]
We also used to use a recursive approach but I found that a bit convoluted.

**Comment by lrennels** [comment]
Idea: can se use `Base.setindex_shape_check` here?

**Comment by lrennels** [comment]
@davidanthoff it would be good to look through this together, I'm not sure I like the current approach but it should work and passes the tests.

**Comment by lrennels** [comment]
@jrising merging, will return to this to think about a more Julia-esque arrays way to handle it

**Pull request merged**
