### PR TITLE
Use travis for Windows testing

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Hm, so I don't really understand why this is not working...

**Comment by lrennels** [comment]
This branches just off of `master` right? Not the doctesting branch?

**Comment by davidanthoff** [comment]
Yes

**Comment by lrennels** [comment]
Then yea, I don't know why this stalling thing is happening either. Maybe I'll ask on Slack.

**Comment by davidanthoff** [comment]
Maybe we should try to disable anything Electron related on this branch, and just try to see whether that fixes it. Something might be going on with Electron...

**Pull request closed without merging**
