### PR TITLE
Rename the 'marginal' attribute of MarginalModel to 'modified'

### PR DESCRIPTION
**Pull request by arnavgautam**
Renames the attribute, and adds an alias for the old 'marginal' name which includes a deprecation warning
See  https://github.com/mimiframework/Mimi.jl/issues/530

### CODE REVIEW

**Comment by arnavgautam** [comment]
Ah yeah I had done manual testing by keeping one of the old lines and running the test suite. The line showed up as a properly formatted warning, but the tests still passed. If you want, I can put that back in, but I figured users would be confused if it showed up for them.

**Comment by ckingdon95** [comment]
The value of keeping it in would be to make sure that the new function you added gets tested properly, but I'm surprised to see that the coverage tests that ran say that 100% of the diff is hit... I would've thought that it would miss those lines... Maybe it's possible that the model tests (i.e. DICE and FUND) that get run by the test suite are hitting those lines of the function... Either way I think it would make sense to just leave one in the test file, and add a comment that says you are testing the soon-to-be-deprecated behavior

**Comment by lrennels** [comment]
Yea I agree, we've done that with some of the other deprecated code, just do leave a note and it'll be easy for us to find it later!

**Comment by arnavgautam** [comment]
Updated it with the test, sorry for the git weirdness but I guess the VSCode interface messed me up

**Comment by ckingdon95** [comment]
@lrennels do you know why some of your most recent commits are showing up here in the diffs of the "Files changed" even though they've already been commited to master?

**Comment by lrennels** [comment]
@ckingdon95 Oh that's strange no I don't know, I was thinking maybe if I approved it would re-compare to master but it didn't. Odd ...

**Comment by lrennels** [comment]
@ckingdon95 I just merged a little toml update so I'll update this branch and see if that helps

**Comment by ckingdon95** [comment]
awesome thanks Lisa!

**Pull request merged**
