### PR TITLE
added a comment to the to Pkg.add("Mimi")

### PR DESCRIPTION
**Pull request by fhoces**
First time running Julia, and `Pkg.add("Mimi") ` was not working until I did `import Pkg`

### CODE REVIEW

**Comment by davidanthoff** [comment]
Thanks for finding this!

@lrennels I think we should instead point folks to the pkg REPL mode and get rid of any code examples that use `Pkg.something`. @lrennels could you track this?

**Comment by lrennels** [comment]
@davidanthoff sure I'll look through the docs now and add a new PR

**Comment by lrennels** [comment]
@davidanthoff @fhoces see #483

**Comment by lrennels** [comment]
This is addressed in #483, so that `import Pkg` will actually not be necessary since use the Pkg mode in the REPL.

**Pull request closed without merging**
