### PR TITLE
Add method for copying params with string or symbol type

### PR DESCRIPTION
**Pull request by lrennels**
Addresses #464 @jrising

### CODE REVIEW

**Comment by lrennels** [comment]
Yes, I tried 

```
using Mimi

@defcomp Example begin
    param::Array{String, 2} = Parameter()

    function run_timestep(p, v, d, t)
    end
end

m = Model()
set_dimension!(m, :time, 1:10)

add_comp!(m, Example)
param = ["a" "b"; "c" "d"]

set_param!(m, :Example, :param, param)

run(m)
```
... and it works even without this PR so I think we're fine although I should probably also look into why that works!

**Comment by jrising** [comment]
@lrennels Thanks for this!  But I'm surprised by the syntax for arrays (although I don't need arrays, so it's not pressing).  Should this be:
```
param::String = Parameter(index=[time])
```

I think it's better to be consistent on the way that Parameters are defined (that is, listing their indices) than to say that the `::` syntax always refers to the whole parameter variable.

**Comment by lrennels** [comment]
I was thinking of this slightly differently, in that the `::` syntax would help us type check the parameter we bind to `param`, in which case it would not be a `String` but an `Array`. @davidanthoff @rjplevin what are your thoughts here?

**Comment by lrennels** [comment]
So still my example was incorrect, but it would be 
```
param::param::Array{String, 2} = Parameter(index=[time])
```

**Comment by rjplevin** [comment]
It's a choice between keeping it simple, in which case it would be:
`paramName::String = Parameter(index=[time])`
vs being somewhat more true to Julia syntax, which would be as Lisa suggested:
` param::Array{String, 1} = Parameter(index=[time])`

(I assume that `param::param::` was a typo, right?)

As a third alternative, we could avoid overloading Julia syntax and add keyword to our Parameter definition, e.g., 
`paramName = Parameter(index=[time], type=String)`

I think it would be less desirable to have to use full Julia syntax on the left side when the right side departs from this, and is somewhat redundant with the `index=` bit.

**Comment by jrising** [comment]
My vote is for your third option, @rjplevin.  I've always felt that the param::Type syntax was a bit clunky.

**Comment by davidanthoff** [comment]
The `paramName::MyType= Parameter(index=[time])` has been around for a long time and I'm pretty sure it is used in a number of places in models. So I think in the interest of not breaking things and not introducing another alternative syntax, I would stick with that.

**Comment by rjplevin** [comment]
I appreciate the desire to avoid breaking things, but I'm not sure that now is the time to lock in choices that we might regret later on for not changing them when the user base was still very small.

We could support both the old style and the new, and recommend using the new syntax, then deprecate the old syntax at some point. A gradual off ramp...

**Comment by lrennels** [comment]
Hmm I'm more inclined to stick with 
```Julia
param::Array{String, 1} = Parameter(index=[time])
```
because it seems more intuitive from a Julia perspective.  It's true that this might seem repetitive in some ways, but it's also not _necessary_ to parameterize `param` in this way so we aren't enforcing repetition.  To me it seems more inconsistent to use the first option
```Julia
param::String = Parameter(index=[time])
```
because it breaks from the intuition of type parameterization.

I can move this to a separate (open) issue for continued discussion, although it's not urgent.

**Pull request merged**
